FROM debian:bullseye-slim

COPY . /build/pkcs11-proxy
WORKDIR /build/pkcs11-proxy

RUN apt-get update \
    && apt-get install -y bash curl git-core build-essential pkg-config cmake cdbs debhelper libssl-dev libseccomp-dev

RUN dpkg-buildpackage -b -rfakeroot -us -uc

CMD /bin/bash